---
title: "simulation_bayesienne_PO"
output: html_document
date: "2024-03-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(truncnorm)
library(mrgsolve)

library(mrgsolve)
library(mapbayr)

library(dplyr)

library(magrittr)
library(ggplot2)
library(PKNCA)
library(ggplot2)
library(ggcorrplot)
```
on télcharge le fichier de simulation test 
```{r}

library(readxl)

auc_test_PO <- read_excel("auc_test_PO.xlsx")

auc_test_lss_mapbayr <-
  auc_test_PO %>% 
  pivot_longer(cols = out_0:out_6, names_to = "time",  values_to = "DV",names_prefix = "out_" )%>% 
  rename(ID = 1)
```

Franck model 

```{r}
code_bene2 <- "

[PROB] #modèle Ganciclovir bjcp Franck et al 2020

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 0.73 : typical Ka (/h)
TVF:  0.43: Typical bioavailability (%)
TV1: 9.7 :  typical V1
TV2: 7.6:  typical  V2
TVQ : 10.9 : typical intercompartmental clearance
TVCL : 6.9 : typical CL 
CrCL: 0.88 : effet of CrCL on CL

ETA1: 0 : Clearance (L/h)
ETA2: 0 : central volume (L)
ETA3: 0 : ka
ETA4: 0 : F

$PARAM @annotated @covariates
WT :26.7 : median current weight 
CLCREA :148.8: median Cl creat 

[OMEGA] 0.19 0.348 0.49 0.096


$SIGMA
0.00 // proportional
0.96 // additive

[CMT] @annotated
DEPOT  : Dosing compartment (mg)[ADM]
CENT : Central compartment [OBS]
PERI : First peripheral compartment 

$TABLE
double DV = (CENT/V1) *(1 + EPS(1)) + EPS(2);

[MAIN]
double Ka = TVKa * exp(ETA3 + ETA(3));
double CL = (TVCL * pow(WT/26.7,0.75) * pow(CLCREA/148.8,CrCL)) * exp(ETA1 + ETA(1));
double Q = TVQ ;
double V1 = (TV1 * WT/26.5) * exp(ETA2 + ETA(2)) ;
double V2 = TV2  * WT/26.5 ;
F_DEPOT= TVF * exp(ETA4 + ETA(4));
ALAG_DEPOT = 0.33;

[ODE]
dxdt_DEPOT = -Ka * DEPOT;
dxdt_CENT = Ka * DEPOT -(CL+Q) * CENT/V1 + Q * PERI/V2 ;
dxdt_PERI = Q * CENT/V1 - Q * PERI/V2 ;

$CAPTURE DV CL V2 V1 Q
"
my_model_bene2 <- mcode("ganciclovir_model", code_bene2)


my_model_bene2 %>% 
  ev(am = 520 ,ss=1, ii=12) %>%
  Req(DV) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()

my_model_bene2 %>% 
  ev(am = 520 ,ss=1, ii=12) %>%
  Req(DV,CL) %>%
  mrgsim(delta = 0.1, end = 24) %>% 
  plot()


data <- expand.ev(ID = 1:10, amt = 520,ii=24, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
sim_bene <- my_model_bene2 %>% 
  data_set(data) %>%
  Req(DV) %>%
 mrgsim(delta = 1, end = 24)#%>% 
  #f#ilter(time==24)
  # plot()
  #filter(time==23.9)


```


```{r}
simul_all_26 <- auc_test_lss_mapbayr %>% filter(time==0  | time==2 | time==6) 


summary(simul_all_26)


#### data preparation
simu_lss_26 <- simul_all_26 %>% 
  # filter(dplyr::between(time,0,23)) %>% 
  mutate( ii=24,ss=1, addl=1, evid = if_else(time==0,1,0),cmt= if_else(evid==1,1,2) ) %>% 
  arrange(ID, time) %>% 
  select(ID, time, amt, ii, ss, addl,SEX,  evid, DV,Pds,cmt,  Clcreat,age,taille,SEX,SC_mosteller, greffe) %>% 
  arrange(ID, time) %>% 
  mutate(mdv = if_else(evid==1, 1, 0)) 

summary(simu_lss_26)

### selected points 2/6

simu_lss_26 <- simu_lss_26 %>% dplyr::filter(time==1 | time==2|time==6|mdv==1) %>%
  group_by(ID, time) %>% slice_head(n=1) %>% ungroup() %>%
  select( -greffe)
simu_lss_26$ID=as.numeric(simu_lss_26$ID)
simu_lss_26$time=as.numeric(simu_lss_26$time)
#simu_lss_26$SEX=as.numeric(simu_lss_26$SEX)

simu_lss_26 <- simu_lss_26 %>% rename(WT=Pds,CLCREA=Clcreat)

est_2_pt <- function(n) {my_model_bene2 %>% 
mapbayest(simu_lss_26 %>% filter(ID == n), hessian=FALSE) %>% as_tibble() }
ind <- c(1:2519)
map_2_pt_data <- map_df(ind, est_2_pt)

map_2_pt_data <- map_2_pt_data %>% mutate(AUCpred=  0.43*amt/CL)
summary(map_2_pt_data)


#### comparison AUC 



auc_test_lss_mapbayr$ID=as.numeric(auc_test_lss_mapbayr$ID)
simul_vraiauc <- auc_test_lss_mapbayr %>% filter(time==0) 

map_2_pt_data_time0 <- map_2_pt_data %>% filter(time==0) 

data_final_2pts<- simul_vraiauc %>% 
  left_join(map_2_pt_data_time0 %>% select(ID, AUCpred)) 
 

data_final_2pts <- data_final_2pts %>% select(auc,AUCpred) %>% mutate (aucmoitie=AUCpred/2)






data_final_2pts  %>% mutate(bias_brut = AUCpred - auc, bias_rel = (AUCpred - auc)/auc,bias_brut_sq = bias_brut*bias_brut,  bias_sq = bias_rel*bias_rel) %>% 
  summarise(
    mean_bias = mean(bias_rel), 
    rmse = sqrt(mean(bias_sq)),
    rmse_brut = sqrt(mean(bias_brut_sq)),
    rsq = rsq_trad_vec(AUCpred, auc),
    biais_out_20percent = mean(!dplyr::between(bias_rel, -0.2, 0.2)),
    nb_out_20percent = sum(!dplyr::between(bias_rel, -0.2, 0.2)),
    n = n()
    )





```

# estimation bayesienne modèle Facchin 

```{r}
code_Facchin2 <- "

[PROB] #modèle Facchin et al 2009 

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 6.96 : typical Ka (/h)
TVALAG:0.86: typical lag time
TV1: 45 :  typical V1
TV2: 18.5:  typical  V2
TVQ : 1.46 : typical intercompartmental clearance
TVCL:9.07 : clearance typique 
CRCL : -0.768 : effect Creat deviation on CL 
CRBSA: 1.31: effet BSA on cl
VBSA: 1.28: effet BSA on V 
CRSEX:1.15 : effet sexe on cl 
VSEX: 1.14: effet SEX on V 

ETA1: 0 : Clearance (L/h)
ETA2: 0 : central volume (L)
ETA3: 0 : v2
ETA4: 0 : ka

[PARAM] @annotated @covariates
BSA :1.08  : median BSA
CREA :72.5: median creat 
SEX : 1 : 1 si garçon 0 si fille 

[CMT] @annotated
DEPOT  : Dosing compartment (mg) [ADM]
CENT : Central compartment [OBS]
PERI : First peripheral compartment 
 

[OMEGA] 0.0256 0.0086 0.298 0.350


[MAIN]
 

double Ka = TVKa*exp(ETA(4) +ETA4);
double CL = TVCL*pow(BSA,CRBSA)*pow(CREA/72.5,CRCL)*pow(CRSEX,SEX)*exp(ETA(1) + ETA1);
double Q = TVQ ;
double V1 = TV1*pow(BSA,VBSA)*pow(VSEX,SEX)*exp(ETA(2)+ ETA2);
double V2 = TV2*exp(ETA(3) +ETA3) ;
ALAG_DEPOT= TVALAG;



[SIGMA] @annotated
PROP:0 : prop error model
ADD: 0.05: additive error log(0.23)

[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 
capture DV = (CENT/V1)+ EPS(1);
int i = 0;
while(DV<0 && i <100) {
simeps();
DV = (CENT/V1)+ EPS(1);
++i;
}

$CAPTURE DV CL V2 V1 Q

"
my_model_facchin2 <- mcode("ganciclovir_model", code_Facchin2)

```

Test 
```{r}
data <- expand.ev(ID = 1:10, amt = 520,ii=24, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
my_model_facchin2 %>% 
  data_set(data) %>%
  Req(DV) %>%
 mrgsim(delta = 1, end = 24) %>% 
  plot()#


```
facchin auc map-be

```{r}
#tes tmaypbayr
my_est <- my_model_facchin2 %>% 
  adm_rows(time = 0, amt = 326, ss=1, ii=24) %>% 
  obs_rows(time = 1, DV = 7.71) %>% 
  obs_rows(time = 2, DV = 11.9) %>% 
  obs_rows(time = 6, DV = 3.52) %>% 
  add_covariates(CREA = 85,BSA=1.1 ,SEX=1) %>% 
  mapbayest()
print(my_est)
plot(my_est)
hist(my_est) 

summary(simu_lss_26)

simu_lss_26 <- simu_lss_26 %>% mutate(CREA=case_when(age<=1~(40*taille/CLCREA),age>1 & age<=12~(49*taille/CLCREA),age>12~(62*taille/CLCREA))) 


simu_lss_26 <- simu_lss_26%>% mutate(SEX2=case_when(SEX=="boy"~"1", SEX=="girl"~"0")) 

simu_lss_26 <- simu_lss_26 %>% select(-SEX) %>% rename(SEX=SEX2)

simu_lss_26$SEX=as.numeric(simu_lss_26$SEX)

est_2_pt <- function(n) {my_model_facchin2 %>% 
mapbayest(simu_lss_26 %>% filter(ID == n), hessian=FALSE) %>% as_tibble() }
ind <- c(1:2519)
#ind<-2
map_2_pt_data <- map_df(ind, est_2_pt)

map_2_pt_data <- map_2_pt_data %>% mutate(AUCpred= amt/CL)
summary(map_2_pt_data)





auc_test_lss_mapbayr$ID=as.numeric(auc_test_lss_mapbayr$ID)
simul_vraiauc <- auc_test_lss_mapbayr %>% filter(time==0) 

map_2_pt_data_time0 <- map_2_pt_data %>% filter(time==0) 

data_final_2pts<- simul_vraiauc %>% 
  left_join(map_2_pt_data_time0 %>% select(ID, AUCpred)) 
 

data_final_2pts <- data_final_2pts %>% select(auc,AUCpred) %>% mutate (aucmoitie=AUCpred/2)


library(yardstick)
data_final_2pts  %>% mutate(bias_brut = AUCpred - auc, bias_rel = (AUCpred - auc)/auc,bias_brut_sq = bias_brut*bias_brut,  bias_sq = bias_rel*bias_rel) %>% 
  summarise(
    mean_bias = mean(bias_rel), 
    rmse = sqrt(mean(bias_sq)),
    rmse_brut = sqrt(mean(bias_brut_sq)),
    rsq = rsq_trad_vec(AUCpred, auc),
    biais_out_20percent = mean(!dplyr::between(bias_rel, -0.2, 0.2)),
    nb_out_20percent = sum(!dplyr::between(bias_rel, -0.2, 0.2)),
    n = n()
    )


```

# modele nguyen

NGuyen's model simulation

```{r}
code_nguyen <- "

[PROB] #modèle Ganciclovir  Nguyen et al 2021

[SET] end=100, delta=0.1

[PARAM] @annotated


TVKa: 0.506 : typical Ka (/h)
TVF:  0.438: Typical bioavailability (%)
TV1: 5.96 :  typical V1
TV2: 1.29:  typical  V2
TVQ : 0.222 : typical intercompartmental clearance
TVCL : 2.55 : etypical CL 
CRCL : 0.763 : effect ClCr deviation on CL 

ETA1:0: eta CL
ETA2:0: eta v

[PARAM] @annotated @covariates
WT :26.7 : median current weight 
CLCREA :148.8: median Cl creat 


[CMT] @annotated
DEPOT  : Dosing compartment (mg) [ADM]
CENT : Central compartment  [OBS]
PERI : First peripheral compartment 
 

[OMEGA] 0.0556 0.0484



[MAIN]
 

double Ka = TVKa;
double CL = TVCL*pow(WT/11.7,0.75)*pow(CLCREA/167,CRCL)*exp(ETA(1)+ ETA1);
double Q = TVQ*pow(WT/11.7,0.75) ;
double V1 = TV1*pow(WT/11.7,1)*exp(ETA(2) + ETA2);
double V2 = TV2*pow(WT/11.7,1) ;
F_DEPOT= TVF;


[SIGMA] @annotated
PROP: 0.0477 : proportionnel error 0.477
ADD:0: additive error


[ODE]
dxdt_DEPOT = -Ka*DEPOT;
dxdt_CENT = Ka*DEPOT -(CL+Q)*CENT/V1 + Q*PERI/V2 ;
dxdt_PERI = Q*CENT/V1 - Q*PERI/V2 ;

[TABLE] 
capture DV = (CENT/V1)* (1+ EPS(1));
int i = 0;
while(DV<0 && i <100) {
simeps();
DV = (CENT/V1)* (1+ EPS(1)) ;
++i;
}

$CAPTURE DV CL V2 V1 Q

"


my_model_nguyen2 <- mcode("ganciclovir_model_nguyen", code_nguyen)

data <- expand.ev(ID = 1:10, amt = 520,ii=12, ss=1)#) #2,2.5,3, 3.5, 4
set.seed(2345)
my_model_nguyen2 %>% 
  data_set(data) %>%
  Req(DV) %>%
 mrgsim(delta = 1, end = 24) %>% 
  plot()#%>% 
  #filter(time==12)
  #plot()
  #filter(time==23.9)

```



Test mapbayr nguyen


```{r}
#tes tmaypbayr
my_est <- my_model_nguyen2 %>% 
  adm_rows(time = 0, amt = 326, ss=1, ii=24) %>% 
  obs_rows(time = 1, DV = 7.71) %>% 
  obs_rows(time = 2, DV = 11.9) %>% 
  obs_rows(time = 6, DV = 3.52) %>% 
  add_covariates(CLCREA = 85, WT=12.5) %>% 
  mapbayest()
print(my_est)
plot(my_est)
hist(my_est) 
#### comparaison des AUC prédites avec 3 points et des AUC vrais 


summary(simu_lss_26)


est_2_pt <- function(n) {my_model_nguyen2 %>% 
mapbayest(simu_lss_26 %>% filter(ID == n), hessian=FALSE) %>% as_tibble() }
ind <- c(1:2519)
#ind<-2
map_2_pt_data <- map_df(ind, est_2_pt)

map_2_pt_data <- map_2_pt_data %>% mutate(AUCpred= 0.438*amt/CL)
summary(map_2_pt_data)





auc_test_lss_mapbayr$ID=as.numeric(auc_test_lss_mapbayr$ID)
simul_vraiauc <- auc_test_lss_mapbayr %>% filter(time==0) 

map_2_pt_data_time0 <- map_2_pt_data %>% filter(time==0) 

data_final_2pts<- simul_vraiauc %>% 
  left_join(map_2_pt_data_time0 %>% select(ID, AUCpred)) 
 

data_final_2pts <- data_final_2pts %>% select(auc,AUCpred) %>% mutate (aucmoitie=AUCpred/2)



data_final_2pts  %>% mutate(bias_brut = AUCpred - auc, bias_rel = (AUCpred - auc)/auc,bias_brut_sq = bias_brut*bias_brut,  bias_sq = bias_rel*bias_rel) %>% 
  summarise(
    mean_bias = mean(bias_rel), 
    rmse = sqrt(mean(bias_sq)),
    rmse_brut = sqrt(mean(bias_brut_sq)),
    rsq = rsq_trad_vec(AUCpred, auc),
    biais_out_20percent = mean(!dplyr::between(bias_rel, -0.2, 0.2)),
    nb_out_20percent = sum(!dplyr::between(bias_rel, -0.2, 0.2)),
    n = n()
    )




```


